### ISSUE TITLE
[FR] Automatically build .jar artifact and release it

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#15]
## Description
As a user, I want to be able to download a new .jar executable a soon as a new version is available.
Automatically add executables to the release when a tag / release is created.

## Steps to finish the task: 

1. Set final name 'contact-manager' for the .jar file in the `pom.xml` file.

``` xml
              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                        ...
                        <configuration>
                              ...
                            <finalName>contact-manager</finalName>
                             ...
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

2. Create a `release.yaml` file under `.github/workflows` folder and paste following script.

![Image](https://github.com/user-attachments/assets/d1738885-9324-4202-9a16-cb25fc3142a0)

``` yaml
name: Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/contact-manager.jar
            LICENSE
```

Hints:

https://github.com/marketplace/actions/gh-release#-usage

https://medium.com/@alexander.volminger/ci-cd-for-java-maven-using-github-actions-d009a7cb4b8f

https://www.youtube.com/watch?v=BqCe-nSXSGI&ab_channel=Thetips4you

The executables should be available in the [releases](https://github.com/JavaRush-GNEW/contact-manager/releases)
![Image](https://github.com/user-attachments/assets/bd8659fa-99ec-4566-86da-929f909340e7)

![Image](https://github.com/user-attachments/assets/f2811328-8879-4ca3-9600-d793b9f7c9ce)
[Source](https://en.wikipedia.org/wiki/Software_versioning)

## Dependencies
- 

## Acceptance criteria
1. .jar is generated in the CI pipeline automatically
2. .jar is available under [releases](https://github.com/JavaRush-GNEW/contact-manager/releases)
